# Pixel sprites shared with the original design. "." is transparent.
LEGS = {
  "stand": ["...KPPPKKPPPK...", "...KPPPKKPPPK...", "...KKKK..KKKK..."],
  "walkA": ["...KPPPKKPPPK...", "...KPPPK.KKKK...", "...KKKK........."],
  "walkB": ["...KPPPKKPPPK...", "...KKKK.KPPPK...", ".........KKKK..."],
}
SIDE_LEGS = {
  "stand": ["...KPPPPPPK.....", "...KPPKKPPK.....", "...KKKK.KKKK...."],
  "walkA": ["...KPPPPPPK.....", "..KPPK..KPPK....", "..KKK....KKK...."],
  "walkB": ["...KPPPPPPK.....", "....KPPPPK......", "....KKKKK......."],
}
BLANK = "................"


IRVING = {
  "down": [
    ".....KKKKKK.....",
    "...KKRRRRRRKK...",
    "..KRRRRWWRRRRK..",
    "..KRRRRWWRRRRK..",
    "..KNNNNNNNNNNK..",
    "..KBSSSSSSSSBK..",
    "..KBSKSSSSKSBK..",
    "..KBSSSBBSSSBK..",
    "..KBBBBssBBBBK..",
    "...KBBBBBBBBK...",
    "....KKSSSSKK....",
    "..KGGGGGGGGGGK..",
    ".KtGGGGGGGGGGSK.",
    ".KtGGGGGGGGGGSK.",
    ".KtKgGGGGGGgKSK.",
    "..KKPPPPPPPPKK..",
  ],
  "up": [
    ".....KKKKKK.....",
    "...KKRRRRRRKK...",
    "..KRRRRRRRRRRK..",
    "..KRRRRRRRRRRK..",
    "..KRRRNNNNRRRK..",
    "..KHHHHHHHHHHK..",
    "..KHHHHHHHHHHK..",
    "..KSHHHHHHHHSK..",
    "...KHHHHHHHHK...",
    "....KSSSSSSK....",
    "....KKSSSSKK....",
    "..KGGGGGGGGGGK..",
    ".KSGGGGGGGGGGtK.",
    ".KSGGGGGGGGGGtK.",
    ".KSKgGGGGGGgKtK.",
    "..KKPPPPPPPPKK..",
  ],
  "side": [
    "....KKKKKK......",
    "...KRRRRRRKK....",
    "..KRRRRRRRRRK...",
    "..KRRRRRRRRRK...",
    "..KRRRRRNNNNNNK.",
    "..KHHSSSSSSK....",
    "..KHSSSSKSSK....",
    "..KHSSSSSSSSK...",
    "..KHBBBBBBBK....",
    "...KBBBBBBK.....",
    "....KSSSSK......",
    "...KGGGGGGK.....",
    "...KGGGtGGK.....",
    "...KGGGtGGK.....",
    "...KgGGtGgK.....",
    "...KPPPPPPK.....",
  ],
}


MOENO = {
  "down": [
    ".....KKKKKK.....",
    "...KKHHHHHHKK...",
    "..KHHHHHHHHHFFK.",
    "..KHHHHHHHHHFfFK",
    "..KHHhHHHHHHHFK.",
    "..KHSSSSSSSSHK..",
    "..KHSKSSSSKSHK..",
    "..KHSSSSSSSSHK..",
    "..KHHSSrrSSHHK..",
    ".KHHHKSSSSKHHHK.",
    ".KHHHKKSSKKHHHK.",
    ".KHHGGGGGGGGHHK.",
    ".KHSGGGGGGGGSHK.",
    ".KHSGGGGGGGGSHK.",
    "..KSKgGGGGgKSK..",
    "..KKPPPPPPPPKK..",
  ],
  "up": [
    ".....KKKKKK.....",
    "...KKHHHHHHKK...",
    ".FFKHHHHHHHHHK..",
    "KFfFHHHHHHHHHK..",
    ".KFHHHHHHHHHHK..",
    "..KHHHHHHhHHHK..",
    "..KHHHHHHHHHHK..",
    ".KHHHHHHHHHHHHK.",
    ".KHHHHHHHHHHHHK.",
    ".KHHHHHHHHHHHHK.",
    ".KHHHHHHHHHHHHK.",
    ".KGHHHHHHHHHHGK.",
    ".KSGHHHHHHHHGSK.",
    ".KSGGHHHHHHGGSK.",
    "..KKgGGGGGGgKK..",
    "..KKPPPPPPPPKK..",
  ],
  "side": [
    "....KKKKKK......",
    "...KHHHHHHKK....",
    "..KHHHHHHHHHK...",
    "..KHHHHHHHHSK...",
    "..KHHHHHSSSSK...",
    "..KHHHHSSSSSK...",
    "..KHHHHSSKSSK...",
    "..KHHHHSSSSSSK..",
    ".KHHHHHHSSrSK...",
    ".KHHHHHHKSSK....",
    ".KHHHHHHGGK.....",
    ".KHHHHHGGGGK....",
    "..KHHHHGSGGK....",
    "...KHHGGSGGK....",
    "...KgGGGSGgK....",
    "...KPPPPPPK.....",
  ],
  
  "leftOverlay": [
    [10, 2, "F"], [11, 2, "F"], [9, 3, "F"], [10, 3, "f"], [11, 3, "F"], [10, 4, "F"],
  ],
}


TOWNSFOLK = {
  "down": [
    BLANK,
    ".....KKKKKK.....",
    "....KHHHHHHK....",
    "...KHHHHHHHHK...",
    "..KHHHHHHHHHHK..",
    "..KHSSSSSSSSHK..",
    "..KSSKSSSSKSSK..",
    "..KSSSSSSSSSSK..",
    "...KSSSssSSSK...",
    "....KKSSSSKK....",
    "...KCCCWWCCCK...",
    "..KCCCCTTCCCCK..",
    ".KSCCCCTTCCCCSK.",
    ".KSCCCCCCCCCCSK.",
    ".KSKCCCCCCCCKSK.",
    "..KKPPPPPPPPKK..",
  ],
}

OUTLINE = "#23202e"
TEE = { "G": "#a3a7b0", "g": "#737883" }

PALETTES = {
  "irving": {
    "K": OUTLINE, "R": "#d8383d", "W": "#f3ede1", "N": "#283272", "H": "#2d211c", "B": "#2d211c",
    "S": "#e2ab85", "s": "#b9776a", "t": "#4c566d", "P": "#2c2e3a", **TEE,
  },
  "moeno": {
    "K": OUTLINE, "H": "#1d1824", "h": "#4b4362", "F": "#56b3ef", "f": "#f6d54c",
    "S": "#f4cfae", "r": "#dd7f7a", "P": "#2c2e3a", **TEE,
  },
  "salaryman": { "K": OUTLINE, "H": "#2a2a33", "S": "#f0c9a4", "s": "#c68a74", "C": "#3b4a6b", "W": "#f4f4f4", "T": "#b8323a", "P": "#2b2f3d" },
  "obaachan": { "K": OUTLINE, "H": "#c9c6cf", "S": "#efc8a6", "s": "#c68a74", "C": "#8a5aa8", "W": "#f1e6f7", "T": "#6d4389", "P": "#4a3b56" },
  "traveler": { "K": OUTLINE, "H": "#7a4c2c", "S": "#f2cfb0", "s": "#c68a74", "C": "#2f8f86", "W": "#e9f5f3", "T": "#f0a13a", "P": "#3a4458" },
  "vendor": { "K": OUTLINE, "H": "#1f1f26", "S": "#e9bf98", "s": "#c68a74", "C": "#f2f0ea", "W": "#f2f0ea", "T": "#d8383d", "P": "#30323d" },
  "guard": { "K": OUTLINE, "H": "#3a2b22", "S": "#dcae88", "s": "#b8806c", "C": "#27335e", "W": "#e8ecf4", "T": "#c9a93b", "P": "#1f2540" },
  "clerk": { "K": OUTLINE, "H": "#2d2233", "S": "#f3cfb0", "s": "#cf8e84", "C": "#f3f5f8", "W": "#ffffff", "T": "#2e7d8c", "P": "#394155" },
  "barista": { "K": OUTLINE, "H": "#5a3a26", "S": "#f2cdae", "s": "#c98879", "C": "#2f6f62", "W": "#f4ebdc", "T": "#f4ebdc", "P": "#3b2f2a" },
  "mui": { "K": OUTLINE, "C": "#e7c796", "W": "#fbf2e0" },
}

MUI = {
  "down": [
    BLANK, BLANK, BLANK,
    "...KK......KK...",
    "..KCCK....KCCK..",
    "..KCCCKKKKCCCK..",
    "..KCCCCCCCCCCK..",
    "..KCKCCCCCCKCK..",
    "..KCCCWWWWCCCK..",
    "...KCCWKKWCCK...",
    "....KKWWWWKK....",
    "...KCCCCCCCCK...",
    "...KCCCCCCCCK...",
    "...KCCKCCKCCK...",
    "...KKK.KK.KKK...",
    BLANK,
  ],
  "up": [
    BLANK, BLANK, BLANK,
    "...KK......KK...",
    "..KCCK....KCCK..",
    "..KCCCKKKKCCCK..",
    "..KCCCCCCCCCCK..",
    "..KCCCCCCCCCCK..",
    "...KCCCCCCCCK...",
    "....KKCCCCKK....",
    "...KCCCCCCCCK...",
    "...KCCCKKCCCK...",
    "...KCCKCCKCCK...",
    "...KCCCCCCCCK...",
    "...KKK.KK.KKK...",
    BLANK,
  ],
  "side": [
    BLANK, BLANK, BLANK, BLANK,
    "..........KK....",
    ".........KCCK...",
    "........KCCCCK..",
    "........KCKCCWK.",
    "...K....KCCCWWKK",
    "..KCK...KKCCWK..",
    "..KCCKKKKCCCCK..",
    "...KCCCCCCCCK...",
    "...KCCCCCCCCK...",
    "...KCKKCCKKCK...",
    "...KK..KK..KK...",
    BLANK,
  ],
}

